
image: Visual Studio 2019

init:
  - git config --global core.autocrlf true

environment:
  matrix:
  - solution: Semester4/BracketsChecker/BracketsChecker.sln

before_build:
  - nuget restore %solution%

build:
  project: $(solution)

test_script:
  - dotnet test %solution%
