
image: Visual Studio 2019

environment:
  matrix:
  - solution_path: sem4\HomeworkOne\HomeworkOne.sln
  - solution_path: sem4\HomeworkTwo\HomeworkTwo.sln

before_build:
  - nuget restore %solution_path%

build_script:
  - msbuild %solution_path%

test_script:
  - dotnet test sem4\HomeworkOne\HomeworkOne.sln
  - dotnet test sem4\HomeworkTwo\HomeworkTwo.sln
