image: Visual Studio 2019

environment:
  matrix:
  - solution: semester4/HomeworkTwo/HomeworkTwo.sln

before_build:
  - nuget restore %solution%

build_script:
  - msbuild %solution_path%

test_script:
  - dotnet test %solution%
